// default package
// Generated Nov 11, 2015 1:54:11 PM by Hibernate Tools 3.4.0.CR1

package com.e_society.model;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Employee generated by hbm2java
 */
@Entity
@Table(name = "employee", catalog = "e_society")
public class Employee implements java.io.Serializable {

	private int empId;
	private String empFname;
	private String empLname;
	private Date joiningDate;
	private String empType;
	private String empAddress;

	public Employee() {
	}

	public Employee(int empId) {
		this.empId = empId;
	}

	public Employee(int empId, String empFname, String empLname,
			Date joiningDate, String empType, String empAddress) {
		this.empId = empId;
		this.empFname = empFname;
		this.empLname = empLname;
		this.joiningDate = joiningDate;
		this.empType = empType;
		this.empAddress = empAddress;
	}

	@Id
	@Column(name = "emp_id", unique = true, nullable = false)
	public int getEmpId() {
		return this.empId;
	}

	public void setEmpId(int empId) {
		this.empId = empId;
	}

	@Column(name = "emp_fname", length = 45)
	public String getEmpFname() {
		return this.empFname;
	}

	public void setEmpFname(String empFname) {
		this.empFname = empFname;
	}

	@Column(name = "emp_lname", length = 45)
	public String getEmpLname() {
		return this.empLname;
	}

	public void setEmpLname(String empLname) {
		this.empLname = empLname;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "joiningDate", length = 0)
	public Date getJoiningDate() {
		return this.joiningDate;
	}

	public void setJoiningDate(Date joiningDate) {
		this.joiningDate = joiningDate;
	}

	@Column(name = "emp_type", length = 45)
	public String getEmpType() {
		return this.empType;
	}

	public void setEmpType(String empType) {
		this.empType = empType;
	}

	@Column(name = "emp_address", length = 45)
	public String getEmpAddress() {
		return this.empAddress;
	}

	public void setEmpAddress(String empAddress) {
		this.empAddress = empAddress;
	}

}
