// default package

// Generated Nov 19, 2015 10:52:13 AM by Hibernate Tools 3.4.0.CR1

package com.e_society.model;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Flatdetails generated by hbm2java
 */
@Entity
@Table(name = "flatdetails", catalog = "e_society")
public class Flatdetails implements java.io.Serializable {

	private int flatid;
	private String flatno;
	private Character wing;

	public Flatdetails() {
	}

	public Flatdetails(int flatid) {
		this.flatid = flatid;
	}

	public Flatdetails(int flatid, String flatno, Character wing) {
		this.flatid = flatid;
		this.flatno = flatno;
		this.wing = wing;
	}

	@Id
	@Column(name = "flatid", unique = true, nullable = false)
	public int getFlatid() {
		return this.flatid;
	}

	public void setFlatid(int flatid) {
		this.flatid = flatid;
	}

	@Column(name = "flatno", length = 45)
	public String getFlatno() {
		return this.flatno;
	}

	public void setFlatno(String flatno) {
		this.flatno = flatno;
	}

	@Column(name = "wing", length = 1)
	public Character getWing() {
		return this.wing;
	}

	public void setWing(Character wing) {
		this.wing = wing;
	}

}
