// default package
// Generated Dec 5, 2015 12:06:34 PM by Hibernate Tools 3.4.0.CR1
package com.e_society.model;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Member generated by hbm2java
 */
@Entity
@Table(name = "member", catalog = "e_society")
public class Member implements java.io.Serializable {

	private String memberId;
	//private User user;
	private String firstname;
	private String lastname;
	private String phonenumber;
	private String flatNo;
	private Character wing;
	private String sscNo;
	private String alternateAddress;
	private String emergencyContact;
	private String email;
	private Date dob;
	private Date livingFrom;
	private String createdBy;
	private Date createdOn;
	private String updatedBy;
	private Date updatedOn;
	private String serviceType;
	private String companyName;
	private double area;
	private Character isOnRent;
	private String parking;
	private int twowheelerparking;
	private int fourwheelerparking;
	
	
	
	//private Set<User> users = new HashSet<User>(0);

	public Member() {
	}

	public Member(String memberId) {
		this.memberId = memberId;
	}

	public Member(String memberId,String firstname,
			String lastname, String phonenumber, String flatNo, Character wing,
			String sscNo, String alternateAddress, String emergencyContact,
			String email, Date dob, Date livingFrom, String createdBy,
			Date createdOn, String updatedBy, Date updatedOn,
			String serviceType, String companyName) {
		this.memberId = memberId;
		this.firstname = firstname;
		this.lastname = lastname;
		this.phonenumber = phonenumber;
		this.flatNo = flatNo;
		this.wing = wing;
		this.sscNo = sscNo;
		this.alternateAddress = alternateAddress;
		this.emergencyContact = emergencyContact;
		this.email = email;
		this.dob = dob;
		this.livingFrom = livingFrom;
		this.createdBy = createdBy;
		this.createdOn = createdOn;
		this.updatedBy = updatedBy;
		this.updatedOn = updatedOn;
		this.serviceType = serviceType;
		this.companyName = companyName;
		}

	@Id
	@Column(name = "member_id", unique = true, nullable = false, length = 45)
	public String getMemberId() {
		return this.memberId;
	}

	public void setMemberId(String memberId) {
		this.memberId = memberId;
	}

	@Column(name = "firstname", length = 45)
	public String getFirstname() {
		return this.firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	@Column(name = "lastname", length = 45)
	public String getLastname() {
		return this.lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	@Column(name = "phonenumber", length = 10)
	public String getPhonenumber() {
		return this.phonenumber;
	}

	public void setPhonenumber(String phonenumber) {
		this.phonenumber = phonenumber;
	}

	@Column(name = "flat_no", length = 45)
	public String getFlatNo() {
		return this.flatNo;
	}

	public void setFlatNo(String flatNo) {
		this.flatNo = flatNo;
	}

	@Column(name = "wing", length = 1)
	public Character getWing() {
		return this.wing;
	}

	public void setWing(Character wing) {
		this.wing = wing;
	}

	@Column(name = "ssc_no", length = 45)
	public String getSscNo() {
		return this.sscNo;
	}

	public void setSscNo(String sscNo) {
		this.sscNo = sscNo;
	}

	@Column(name = "alternate_address", length = 45)
	public String getAlternateAddress() {
		return this.alternateAddress;
	}

	public void setAlternateAddress(String alternateAddress) {
		this.alternateAddress = alternateAddress;
	}

	@Column(name = "emergency_contact", length = 45)
	public String getEmergencyContact() {
		return this.emergencyContact;
	}

	public void setEmergencyContact(String emergencyContact) {
		this.emergencyContact = emergencyContact;
	}

	@Column(name = "email", length = 45)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dob", length = 0)
	public Date getDob() {
		return this.dob;
	}

	public void setDob(Date dob) {
		this.dob = dob;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "living_from", length = 0)
	public Date getLivingFrom() {
		return this.livingFrom;
	}

	public void setLivingFrom(Date livingFrom) {
		this.livingFrom = livingFrom;
	}

	@Column(name = "createdBy", length = 45)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createdOn", length = 0)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Column(name = "updatedBy", length = 45)
	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updatedOn", length = 0)
	public Date getUpdatedOn() {
		return this.updatedOn;
	}

	public void setUpdatedOn(Date updatedOn) {
		this.updatedOn = updatedOn;
	}

	@Column(name = "service_type", length = 45)
	public String getServiceType() {
		return this.serviceType;
	}

	public void setServiceType(String serviceType) {
		this.serviceType = serviceType;
	}

	@Column(name = "company_name", length = 45)
	public String getCompanyName() {
		return this.companyName;
	}

	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}
	
	@Column(name = "area")
	public double getArea() {
		return area;
	}

	public void setArea(double area) {
		this.area = area;
	}
	
	@Column(name = "isOnRent")
	public Character getIsOnRent() {
		return isOnRent;
	}

	public void setIsOnRent(Character isOnRent) {
		this.isOnRent = isOnRent;
	}
	
	@Column(name = "parking")
	public String getParking() {
		return parking;
	}

	public void setParking(String parking) {
		this.parking = parking;
	}

	@Column(name="2wheelerparking")
	public int getTwowheelerparking() {
		return twowheelerparking;
	}

	public void setTwowheelerparking(int twowheelerparking) {
		this.twowheelerparking = twowheelerparking;
	}

	@Column(name="4wheelerparking")
	public int getFourwheelerparking() {
		return fourwheelerparking;
	}

	public void setFourwheelerparking(int fourwheelerparking) {
		this.fourwheelerparking = fourwheelerparking;
	}


}
