// default package
// Generated Jul 11, 2016 12:29:04 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Visitor generated by hbm2java
 */
@Entity
@Table(name = "visitor", catalog = "e_society")
public class Visitor implements java.io.Serializable {

	private int visitorId;
	private String visitorName;
	private Date inTime;
	private Date outTime;
	private String comingFrom;
	private String whomToMeet;
	private String flatNumber;
	private String createdBy;
	private String updatedBy;
	private Date createdOn;
	private Date updatedOn;

	public Visitor() {
	}

	public Visitor(int visitorId) {
		this.visitorId = visitorId;
	}

	public Visitor(int visitorId, String visitorName, Date inTime,
			Date outTime, String comingFrom, String whomToMeet,
			String flatNumber, String createdBy, String updatedBy,
			Date createdOn, Date updatedOn) {
		this.visitorId = visitorId;
		this.visitorName = visitorName;
		this.inTime = inTime;
		this.outTime = outTime;
		this.comingFrom = comingFrom;
		this.whomToMeet = whomToMeet;
		this.flatNumber = flatNumber;
		this.createdBy = createdBy;
		this.updatedBy = updatedBy;
		this.createdOn = createdOn;
		this.updatedOn = updatedOn;
	}

	@Id
	@Column(name = "visitorId", unique = true, nullable = false)
	public int getVisitorId() {
		return this.visitorId;
	}

	public void setVisitorId(int visitorId) {
		this.visitorId = visitorId;
	}

	@Column(name = "visitorName", length = 20)
	public String getVisitorName() {
		return this.visitorName;
	}

	public void setVisitorName(String visitorName) {
		this.visitorName = visitorName;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "inTime", length = 0)
	public Date getInTime() {
		return this.inTime;
	}

	public void setInTime(Date inTime) {
		this.inTime = inTime;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "outTime", length = 0)
	public Date getOutTime() {
		return this.outTime;
	}

	public void setOutTime(Date outTime) {
		this.outTime = outTime;
	}

	@Column(name = "comingFrom", length = 20)
	public String getComingFrom() {
		return this.comingFrom;
	}

	public void setComingFrom(String comingFrom) {
		this.comingFrom = comingFrom;
	}

	@Column(name = "whomToMeet", length = 20)
	public String getWhomToMeet() {
		return this.whomToMeet;
	}

	public void setWhomToMeet(String whomToMeet) {
		this.whomToMeet = whomToMeet;
	}

	@Column(name = "flatNumber", length = 20)
	public String getFlatNumber() {
		return this.flatNumber;
	}

	public void setFlatNumber(String flatNumber) {
		this.flatNumber = flatNumber;
	}

	@Column(name = "createdBy", length = 20)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Column(name = "updatedBy", length = 20)
	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "createdOn", length = 0)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "updatedOn", length = 0)
	public Date getUpdatedOn() {
		return this.updatedOn;
	}

	public void setUpdatedOn(Date updatedOn) {
		this.updatedOn = updatedOn;
	}

}
